### ISSUE TITLE
`org.freedesktop.portal.*` permission is not necessary

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.zocker_160.SyncThingy#54]
This will be blocked in the linter soon. This issue is a heads-up for that.

See https://github.com/flathub-infra/flatpak-builder-lint/issues/178

**Comment by zocker-160** [comment]
Thanks for this information @bbhtt, so you are essentially telling me that this has never been required?

If yes, then I wonder about this issue I had for quite some time (still there in Linux Mint) https://github.com/zocker-160/SyncThingy/issues/6 where setting the background permission in Flatseal only was possible if `--talk-name=org.freedesktop.portal.Background` or how does Flatseal determine when to grey that toggle out and when not?

**Comment by bbhtt** [comment]
>  so you are essentially telling me that this has never been required?

Yes


Your desktop environment is supposed to show a permission dialogue when an app wants to run in the background, with allow or deny opetions. The toggle in Flatseal, or your system settings controls that. You can also set it to allow/deny with `flatpak permission-set background background <appid> yes`

> where setting the background permission in Flatseal only was possible if 

That should not be the case, probably something is wrong with portals on your system.

**Comment by zocker-160** [comment]
> That should not be the case, probably something is wrong with portals on your system.

Yes there is, because Linux Mint Cinnamon does not implement the background portal, so the entry is greyed out in Flatseal and of course by portal request fails, which causes the error message.
